DROP INDEX soul_torture_id_idx_hash;
DROP INDEX work_list_work_id_idx_hash;
DROP INDEX work_list_soul_id_idx_hash;
DROP INDEX sin_type_distribution_list_sin_type_id_idx_hash;
DROP INDEX sin_type_distribution_list_event_id_idx_hash;
DROP INDEX soul_handler_id_idx_hash;
DROP INDEX event_handler_id_idx_hash;
DROP INDEX complaint_handler_id_idx_hash;

DROP TRIGGER tr_authorize_after_creating ON _user;
DROP TRIGGER tr_authorize ON _user;
DROP TRIGGER tr_create_sin_type ON sin_type;
DROP TRIGGER tr_create_work ON work;
DROP TRIGGER tr_update_work ON work;
DROP TRIGGER tr_delete_from_sin_type_distribution_list ON sin_type_distribution_list;
DROP TRIGGER tr_delete_from_work_list ON work_list;
DROP TRIGGER tr_delete_soul ON soul;
DROP TRIGGER tr_delete_user ON _user;
DROP TRIGGER tr_distribute_soul_by_hand ON soul;
DROP TRIGGER tr_handle_complaint ON complaint;
DROP TRIGGER tr_handle_event ON _event;
DROP TRIGGER tr_handle_event_through_list ON sin_type_distribution_list;
DROP TRIGGER tr_handle_sin_type ON sin_type;
DROP TRIGGER tr_make_soul_working ON work_list;
DROP TRIGGER tr_update_event_list ON sin_type_distribution_list;
DROP TRIGGER tr_update_work_list ON work_list;
DROP TRIGGER tr_create_monster ON monster;
DROP TRIGGER tr_update_monster ON monster;
DROP TRIGGER tr_create_complaint ON complaint;
DROP TRIGGER tr_create_soul ON soul;
DROP TRIGGER tr_create_torture ON torture;

DROP MATERIALIZED VIEW active_user;
DROP VIEW unhandled_souls;
DROP VIEW unhandled_tortures;
DROP VIEW unhandled_sin_types;
DROP VIEW unhandled_complaints;
DROP VIEW unhandled_events;
DROP VIEW souls_handled_by_users;
DROP VIEW events_handled_by_users;
DROP VIEW complaints_handled_by_users;
DROP VIEW tartar_locations;

DROP TABLE work_list;
DROP TABLE sin_type_distribution_list;
DROP TABLE work;
DROP TABLE _event;
DROP TABLE complaint;
DROP TABLE _status;
DROP TABLE sin_type;
DROP TABLE soul;
DROP TABLE torture;
DROP TABLE monster;
DROP TABLE _location;
DROP TABLE _level;
DROP TABLE _user;
DROP TABLE person;